# Generated by Django 3.1.1 on 2020-09-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddam', '0004_auto_20200903_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='mission',
        ),
    ]
